[package]
name = "eclipse-messaging"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "time", "test-util"] }
